USE [master]
GO

/****** Object:  Database [AWMSdb]    Script Date: 9/4/2024 8:00:00 AM ******/
CREATE DATABASE [AWMSdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AWMSdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MS2019\MSSQL\DATA\AWMSdb.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AWMSdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MS2019\MSSQL\DATA\AWMSdb_log.ldf' , SIZE = 532480KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AWMSdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AWMSdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AWMSdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AWMSdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AWMSdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AWMSdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [AWMSdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AWMSdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AWMSdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AWMSdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AWMSdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AWMSdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AWMSdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AWMSdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AWMSdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AWMSdb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AWMSdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AWMSdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AWMSdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AWMSdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AWMSdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AWMSdb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AWMSdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AWMSdb] SET RECOVERY FULL 
GO

ALTER DATABASE [AWMSdb] SET  MULTI_USER 
GO

ALTER DATABASE [AWMSdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AWMSdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AWMSdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AWMSdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AWMSdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AWMSdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AWMSdb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AWMSdb] SET  READ_WRITE 
GO

